version: '2.3'
services:
  crawler:
    build:
      context: ..
      target: base
    command: compose/develop
    environment:
      PYTHONPATH: .
    ports:
      - '9200:9200' # elastic
      - '5601:5601' # kibana
      - '8082:8082' # luigi
      - '9000:9000' # supervisord
      - '5000:5000' # flask
    volumes:
      - ..:/app
