{
 "title": "PGCAT Query",
 "description": "PostgreSQL Catalog Explorer for Query",
 "tags": [
  "PGCAT",
  "Database",
  "Query"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{ins=\"$ins\"}, datname)"
    }
   },
   {
    "name": "query",
    "label": "Query",
    "query": "SELECT queryid::TEXT FROM monitor.pg_stat_statements pgs, pg_database pgb\nWHERE pgb.oid = pgs.dbid AND pgb.datname = '$datname' ORDER BY total_time / calls DESC LIMIT 1000;"
   },
   {
    "name": "qs",
    "query": "SELECT query FROM monitor.pg_stat_statements WHERE queryid = '$query' LIMIT 1;"
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "ins = ${ins}, used as unique instance identifier. Formed as {{ cls }}-{{ seq }}. ",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "Database name",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Query Identifier",
   "type": "stat",
   "description": "Query identifier generated from plan",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Query String",
   "type": "text",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 2 },
   "options": { "content": "${qs}" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "description": "Users list that runs this query",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT array_agg(u.usename)::TEXT\nFROM monitor.pg_stat_statements s LEFT OUTER JOIN pg_user u ON s.userid = u.usesysid\nWHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT * FROM monitor.pg_stat_statements WHERE queryid = '$query' ORDER BY calls DESC LIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 19, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT * FROM monitor.pg_stat_statements WHERE queryid = '$query' ORDER BY calls DESC LIMIT 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM monitor.pg_stat_statements WHERE queryid = '$query' ORDER BY calls DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{query=\"$query\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "Query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{query=\"$query\"}[1m]) / increase(pg_query_calls{query=\"$query\"}[1m])",
     "legendFormat": "1m"
    },
    {
     "expr": "increase(pg_query_exec_time{query=\"$query\"}[5m]) / increase(pg_query_calls{query=\"$query\"}[5m])",
     "legendFormat": "5m"
    },
    {
     "expr": "increase(pg_query_exec_time{query=\"$query\"}[15m]) / increase(pg_query_calls{query=\"$query\"}[15m])",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Statements Stat for ${query}",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT s.*, u.usename\nFROM monitor.pg_stat_statements s LEFT OUTER JOIN pg_user u ON s.userid = u.usesysid\nWHERE queryid = '$query';"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Statements",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT queryid::TEXT AS qid, *\nFROM monitor.pg_stat_statements s ORDER BY max_time / calls DESC LIMIT 50;"
    }
   ]
  },
  {
   "title": "Active backend queries",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "WITH\n      metrics AS (\n        SELECT\n          application_name,\n          pid,\n          query,\n          SUM(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - state_change))::bigint)::float AS process_idle_seconds_sum,\n          COUNT(*) AS process_idle_seconds_count\n        FROM pg_stat_activity\n        WHERE state = 'active'\n        AND backend_type = 'client backend'\n        GROUP BY application_name, pid, query\n      ),\n      buckets AS (\n        SELECT\n          application_name,\n          le,\n          SUM(\n            CASE WHEN EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - state_change)) <= le\n              THEN 1\n              ELSE 0\n            END\n          )::bigint AS bucket\n        FROM\n          pg_stat_activity,\n          UNNEST(ARRAY[1, 2, 5, 15, 30, 60, 90, 120, 300]) AS le\n        GROUP BY application_name, pid, query, le\n        ORDER BY application_name, le\n      )\n    SELECT\n      application_name,\n      pid,\n      query,\n      process_idle_seconds_sum / 60 as minute_sum\n    FROM metrics JOIN buckets USING (application_name)\n    GROUP BY 1, 2, 3, 4;"
    }
   ]
  }
 ]
}