{
 "title": "PGSQL Xacts",
 "description": "PostgreSQL Transaction detail for instance",
 "tags": [
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Postgres Xacts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transaction Commit",
   "type": "timeseries",
   "description": "Pgbouncer transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:ins:xact_commit_rate5m{ins=\"$ins\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:ins:xact_commit_rate15m{ins=\"$ins\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Transaction Rollback",
   "type": "timeseries",
   "description": "postgres rollbacked transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Transaction Commit Divergence",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(pg:ins:xact_commit_rate1m{ins=\"$ins\"}[5m]) / stddev_over_time(pg:ins:xact_commit_rate1m{ins=\"$ins\"}[5m])) ^ 2",
     "legendFormat": "QPS Divergence"
    }
   ]
  },
  {
   "title": "Rollback",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "Rollback Rate"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:db:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "SAGE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_tx_duration{ins=\"$ins\", state!~\"(idle.*|disabled)\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Locks Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg_lock_count{ins=\"$ins\"})",
     "legendFormat": "Locks"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{ins=\"$ins\"})",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Locks by Category",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:xlock_count{ins=\"$ins\"}",
     "legendFormat": "Exclusive"
    },
    {
     "expr": "pg:ins:wlock_count{ins=\"$ins\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "pg:ins:rlock_count{ins=\"$ins\"}",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}