{
 "title": "PGSQL Node",
 "description": "PGSQL Node Instance Dashboard",
 "tags": [
  "PGSQL",
  "Instance",
  "Node"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "id", "label": "Node ID", "query": { "query": "label_values(node:ins,id)" } },
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(node:ins{id=\"$id\"}, ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(node:ins{id=\"$id\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node:ins{id=\"$id\"}, nodename)"
    }
   },
   {
    "name": "ip",
    "label": "Node IP",
    "query": {
     "query": "label_values(node:ins{ins=\"$ins\"} , instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node IP",
   "type": "stat",
   "description": "Node IP Address ${ip}.  Unique identifier for node",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Node Name",
   "type": "stat",
   "description": "Node Hostname = ${node}",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "All instances in pgsql cluster ${cls}",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "pg:ins:status{cls=\"$cls\"}"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\"}"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "ins = ${ins}, used as unique instance identifier. Formed as {{ cls }}-{{ seq }}. ",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Kernel",
   "type": "stat",
   "description": "Kernel Name",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{ins=\"$ins\"} ",
     "legendFormat": "{{ sysname }}"
    }
   ]
  },
  {
   "title": "Arch",
   "type": "stat",
   "description": "Processor Architecture : (x86_64, arm64,...)",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{ins=\"$ins\"} ",
     "legendFormat": "{{ machine }}"
    }
   ]
  },
  {
   "title": "Release",
   "type": "stat",
   "description": "OS Release",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{ins=\"$ins\"} ",
     "legendFormat": "{{ release }}"
    }
   ]
  },
  {
   "title": "Core",
   "type": "stat",
   "description": "Number of available cpu core",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_count{ins=\"$ins\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "stat",
   "description": "Size of available memory",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ins) (node_memory_MemTotal_bytes{ins=\"$ins\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "description": "Size of available disk space",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (mountpoint)(node_filesystem_size_bytes{ins=\"$ins\"}))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Link",
   "type": "stat",
   "description": "Net interface link speed",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "- absent(node_network_speed_bytes{ins=\"$ins\"}) OR max by (ins) (node_network_speed_bytes{ins=\"$ins\"}) * 8"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage{ins=\"$ins\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:stdload1{ins=\"$ins\"}",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:ins:mem_commit_ratio{ins=\"$ins\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{ins=\"$ins\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:fd_usage{ins=\"$ins\"}",
     "legendFormat": "FD"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:inode_usage{ins=\"$ins\"})",
     "legendFormat": "iNode"
    }
   ]
  },
  {
   "title": "Numa",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "- absent(node_vmstat_numa_hit{ins=\"$ins\"}) OR rate(node_vmstat_numa_hit{ins=\"$ins\"}[5m]) > bool 0"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "description": "Size of available swap",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ins) (node_memory_SwapTotal_bytes{ins=\"$ins\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "PCI-E SSD",
   "type": "stat",
   "description": "Size of available pci-e nvme disk space",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{ins=\"$ins\",device=~\"/dev/dfa.*\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Bond",
   "type": "stat",
   "description": "Is any network interface in bond mode?",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-absent(node_bonding_active{ins=\"$ins\"}) or node_bonding_active{ins=\"$ins\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node:dev:disk_iops_1m{ins=\"$ins\"})",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:disk_io_bytes_rate1m{ins=\"$ins\"}",
     "legendFormat": "Disk IO"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:network_io_bytes_rate1m{ins=\"$ins\"}",
     "legendFormat": "Net Traff"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:tcp_error_rate1m{ins=\"$ins\"}",
     "legendFormat": "TCP Errs"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:tcp_retrans_ratio1m{ins=\"$ins\"}",
     "legendFormat": "Retrans"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(node_ntp_offset_seconds{ins=\"$ins\"}))",
     "legendFormat": "NTP Offset"
    },
    {
     "expr": "node_ntp_sanity{ins=\"$ins\"}",
     "legendFormat": "NTP Sanity"
    }
   ]
  },
  {
   "title": "Machine",
   "type": "stat",
   "description": "Is this machine a virtual machine or physical (Simply Judge by cpu count)",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_count{ins=\"$ins\"} > bool 8",
     "legendFormat": "Res"
    }
   ]
  },
  {
   "title": "Huge Page",
   "type": "stat",
   "description": "Anonymous Huge Page Size",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ins) (node_memory_AnonHugePages_bytes{ins=\"$ins\"})",
     "legendFormat": "HP"
    }
   ]
  },
  {
   "title": "Aliveness",
   "type": "stat",
   "description": "Is current node exporter alive?",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{ins=\"$ins\", instance=~\".*:(9100|9099)\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time since node boot",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time() - node_boot_time_seconds{ins=\"$ins\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:fs:space_usage{ins=\"$ins\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage{ins=\"$ins\"}",
     "legendFormat": "Realtime"
    },
    {
     "expr": "node:ins:cpu_usage_1m{ins=\"$ins\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node:ins:cpu_usage_5m{ins=\"$ins\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node:ins:cpu_usage_15m{ins=\"$ins\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represent an alerting Event. Gray transparent stipe are pending alerts.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"firing\", category=\"node\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}}"
    },
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"pending\", category=\"node\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}}"
    }
   ]
  },
  { "title": "Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage{ins=\"$ins\"}",
     "legendFormat": "Realtime"
    },
    {
     "expr": "node:ins:cpu_usage_1m{ins=\"$ins\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node:ins:cpu_usage_5m{ins=\"$ins\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node:ins:cpu_usage_15m{ins=\"$ins\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Time by State (per Second)",
   "type": "timeseries",
   "description": "Sum of all state will approximately to the number of cpu core",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(node_cpu_seconds_total{ins=\"$ins\"}[5m]))",
     "legendFormat": "{{ mode }}"
    },
    {
     "expr": "sum(node:ins:cpu_count{ins=\"$ins\"})",
     "legendFormat": "CPU Count"
    }
   ]
  },
  {
   "title": "Core Usage Realtime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:cpu:usage{ins=\"$ins\"}",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node:cpu:usage_avg15m{ins=\"$ins\"}",
     "legendFormat": "C{{ cpu }}"
    }
   ]
  },
  { "title": "Schedule", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Load (1m, 5m, 15m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{ins=\"$ins\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{ins=\"$ins\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{ins=\"$ins\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Normalized Load (1m, 5m, 15m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:ins:stdload1{ins=\"$ins\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node:ins:stdload5{ins=\"$ins\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node:ins:stdload15{ins=\"$ins\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Scheduled Timeslices",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node:cpu:sched_timeslices_rate1m{ins=\"$ins\"}",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Schedule Waiting Time",
   "type": "timeseries",
   "description": "How long processes had to be wait to be scheduled on that CPU.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_schedstat_waiting_seconds_total{ins=\"$ins\"}[5m])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Process State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_procs_running{ins=\"$ins\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "node_procs_blocked{ins=\"$ins\"}",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Non-Sleep Process State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_processes_state{ins=\"$ins\", state!=\"S\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Thread",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_processes_threads{ins=\"$ins\"}",
     "legendFormat": "Thread"
    }
   ]
  },
  {
   "title": "Context Switch",
   "type": "timeseries",
   "description": "Context switch rate 1m",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node:ins:ctx_switch_rate1m{ins=\"$ins\"}",
     "legendFormat": "Ctx Switch"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_processes_max_processes{ins=\"$ins\"}",
     "legendFormat": "Max Process"
    },
    {
     "expr": "node_processes_max_threads{ins=\"$ins\"}",
     "legendFormat": "Max Thread"
    }
   ]
  },
  {
   "title": "Fork",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node:ins:forks_rate1m{ins=\"$ins\"}",
     "legendFormat": "Fork"
    }
   ]
  },
  {
   "title": "Interrupt",
   "type": "timeseries",
   "description": "Interrupt Rate 1m",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node:ins:interrupt_rate1m{ins=\"$ins\"}",
     "legendFormat": "Interrupt"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Memory & Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:ins:mem_usage{ins=\"$ins\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "node:ins:swap_usage{ins=\"$ins\"}",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Available Mem",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:ins:mem_avail{ins=\"$ins\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-absent(node_edac_correctable_errors_total) or sum(node_edac_correctable_errors_total{ins=\"$ins\"})",
     "legendFormat": "EDAC Errors"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-absent(node_edac_uncorrectable_errors_total{ins=\"$ins\"}) or sum(node_edac_uncorrectable_errors_total{ins=\"$ins\"})",
     "legendFormat": "Uncorrectable"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{ins=\"$ins\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Cached_bytes{ins=\"$ins\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{ins=\"$ins\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_PageTables_bytes{ins=\"$ins\"}",
     "legendFormat": "PageTable"
    },
    {
     "expr": "node_memory_Slab_bytes{ins=\"$ins\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_Shmem_bytes{ins=\"$ins\"}",
     "legendFormat": "Shmem"
    }
   ]
  },
  {
   "title": "Memory Active/Anonymous Structure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_DirectMap4k_bytes{ins=\"$ins\"}",
     "legendFormat": "4KB"
    },
    {
     "expr": "node_memory_DirectMap2M_bytes{ins=\"$ins\"}",
     "legendFormat": "1MB"
    },
    {
     "expr": "node_memory_DirectMap1G_bytes{ins=\"$ins\"}",
     "legendFormat": "1GB"
    }
   ]
  },
  {
   "title": "Committed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{ins=\"$ins\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_CommitLimit_bytes{ins=\"$ins\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory Active/Anonymous Structure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_Inactive_file_bytes{ins=\"$ins\"}",
     "legendFormat": "Inactive-File"
    },
    {
     "expr": "node_memory_Inactive_anon_bytes{ins=\"$ins\"}",
     "legendFormat": "Inactive-Anon"
    },
    {
     "expr": "node_memory_Active_file_bytes{ins=\"$ins\"}",
     "legendFormat": "Active-File"
    },
    {
     "expr": "node_memory_Active_anon_bytes{ins=\"$ins\"}",
     "legendFormat": "Active-Anon"
    }
   ]
  },
  {
   "title": "Writeback / Dirty",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_Writeback_bytes{ins=\"$ins\"}",
     "legendFormat": "Writeback"
    },
    {
     "expr": "node_memory_Dirty_bytes{ins=\"$ins\"}",
     "legendFormat": "Dirty"
    }
   ]
  },
  {
   "title": "Committed Ratio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_memory_Committed_AS_bytes{ins=\"$ins\"} / node_memory_CommitLimit_bytes{ins=\"$ins\"}",
     "legendFormat": "Commit Ratio"
    }
   ]
  },
  {
   "title": "Page In/Out Rate",
   "type": "timeseries",
   "description": "Rate of pages in/out/swapin/swapout",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node:ins:pagein_rate1m{ins=\"$ins\"}",
     "legendFormat": "▲PageIn"
    },
    {
     "expr": "- node:ins:pageout_rate1m{ins=\"$ins\"}",
     "legendFormat": "▼PageOut"
    }
   ]
  },
  {
   "title": "Swap In/Out Rate",
   "type": "timeseries",
   "description": "Rate of pages in/out/swapin/swapout",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node:ins:swapin_rate1m{ins=\"$ins\"}",
     "legendFormat": "▲SwapIn"
    },
    {
     "expr": "- node:ins:swapout_rate1m{ins=\"$ins\"}",
     "legendFormat": "▼SwapOut"
    }
   ]
  },
  {
   "title": "Major Page Fault",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node:ins:pgmajfault_rate1m{ins=\"$ins\"}",
     "legendFormat": "PageFault"
    }
   ]
  },
  {
   "title": "Page Fault",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node:ins:pagefault_rate1m{ins=\"$ins\"}",
     "legendFormat": "PageFault"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Disk iostat",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (device) (node:dev:disk_util_1m{ins=\"$ins\"})",
     "legendFormat": "util"
    },
    {
     "expr": "max by (device) (node:dev:disk_avg_queue_size{ins=\"$ins\"})",
     "legendFormat": "queue"
    },
    {
     "expr": "max by (device) (node:dev:disk_reads_rate1m{ins=\"$ins\"})",
     "legendFormat": "r/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_writes_rate1m{ins=\"$ins\"})",
     "legendFormat": "w/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_mreads_rate1m{ins=\"$ins\"})",
     "legendFormat": "mr/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_mwrites_rate1m{ins=\"$ins\"})",
     "legendFormat": "mw/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_read_bytes_rate1m{ins=\"$ins\"})",
     "legendFormat": "rb/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_write_bytes_rate1m{ins=\"$ins\"})",
     "legendFormat": "wb/s"
    },
    {
     "expr": "max by (device) (node:dev:disk_read_rt_1m{ins=\"$ins\"})",
     "legendFormat": "r_await"
    },
    {
     "expr": "max by (device) (node:dev:disk_write_rt_1m{ins=\"$ins\"})",
     "legendFormat": "w_await"
    },
    {
     "expr": "max by (device) (node:dev:disk_read_batch_1m{ins=\"$ins\"})",
     "legendFormat": "rreq-sz"
    },
    {
     "expr": "max by (device) (node:dev:disk_write_batch_1m{ins=\"$ins\"})",
     "legendFormat": "wreq-sz"
    }
   ]
  },
  {
   "title": "Read/Write IOPS",
   "type": "timeseries",
   "description": "▲ for read IOPS, ▼ for write IOPS ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node:dev:disk_reads_rate1m{ins=\"$ins\"}",
     "legendFormat": "▲{{ device }}"
    },
    {
     "expr": "- node:dev:disk_writes_rate1m{ins=\"$ins\"}",
     "legendFormat": "▼{{ device }}"
    }
   ]
  },
  {
   "title": "Read/Write Bandwidth",
   "type": "timeseries",
   "description": "▲ for read bandwidth, ▼ for write bandwidth",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:dev:disk_read_bytes_rate1m{ins=\"$ins\"}",
     "legendFormat": "▲{{ device }}"
    },
    {
     "expr": "- node:dev:disk_write_bytes_rate1m{ins=\"$ins\"}",
     "legendFormat": "▼{{ device }}"
    }
   ]
  },
  {
   "title": "Reads/Writes Merged Ratio",
   "type": "timeseries",
   "description": "Merged ratio of read / write requests\n▲ for read ▼ for write",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:dev:disk_mreads_ratio1m{ins=\"$ins\"}",
     "legendFormat": "▲{{ device }}"
    },
    {
     "expr": "- node:dev:disk_mwrites_ratio1m{ins=\"$ins\"}",
     "legendFormat": "▼{{ device }}"
    }
   ]
  },
  {
   "title": "Read/Write Request Size (areq-sz)",
   "type": "timeseries",
   "description": "▲ for read, ▼ for write, Showing I/O pattern",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node:dev:disk_read_batch_1m{ins=\"$ins\"}",
     "legendFormat": "▲{{ device }}"
    },
    {
     "expr": "- node:dev:disk_write_batch_1m{ins=\"$ins\"}",
     "legendFormat": "▼{{ device }}"
    }
   ]
  },
  {
   "title": "Read/Write Await Time",
   "type": "timeseries",
   "description": "▲ for read rt, ▼ for write rt",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node:dev:disk_read_rt_1m{ins=\"$ins\"}",
     "legendFormat": "▲{{ device }}"
    },
    {
     "expr": "- node:dev:disk_write_rt_1m{ins=\"$ins\"}",
     "legendFormat": "▼{{ device }}"
    }
   ]
  },
  {
   "title": "Average Service Time (svctm)",
   "type": "timeseries",
   "description": "▲ for read rt, ▼ for write rt",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node:dev:disk_io_rt_1m{ins=\"$ins\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Instant Queue Size",
   "type": "timeseries",
   "description": "Number of items which were in the queue at the sampling time point",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_disk_io_now{ins=\"$ins\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Average Queue Size",
   "type": "timeseries",
   "description": "average number of operations waiting to be serviced.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node:dev:disk_avg_queue_size{ins=\"$ins\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node:fs:size_bytes{ins=\"$ins\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "max by (device) (node:fs:avail_bytes{ins=\"$ins\"})",
     "legendFormat": "Avail"
    },
    {
     "expr": "max by (device) (node:fs:size_bytes{ins=\"$ins\"} - node:fs:avail_bytes{ins=\"$ins\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "max by (device) (node:fs:space_usage{ins=\"$ins\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "max by (device) (node:fs:inode_total{ins=\"$ins\"})",
     "legendFormat": "iNodes"
    },
    {
     "expr": "max by (device) (node:fs:inode_free{ins=\"$ins\"})",
     "legendFormat": "iNode Free"
    },
    {
     "expr": "max by (device) (node:fs:inode_used{ins=\"$ins\"})",
     "legendFormat": "iNode Used"
    },
    {
     "expr": "max by (device) (node:fs:inode_usage{ins=\"$ins\"})",
     "legendFormat": "iNode Usage"
    },
    {
     "expr": "min by (device) (node_filesystem_readonly{ins=\"$ins\", fstype!~\"(n|root|tmp)fs.*\"})",
     "legendFormat": "iNode Usage"
    }
   ]
  },
  {
   "title": "Space Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:fs:space_usage{ins=\"$ins\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Avail Space 1D Predict",
   "type": "stat",
   "description": "Prediction of avail filesystem space a day later!",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:fs:space_predict_1d{ins=\"$ins\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "iNode Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:fs:inode_usage{ins=\"$ins\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Device Error",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_device_error{ins=\"$ins\", fstype!~\"(n|root|tmp)fs.*\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Space Derive 1h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node:fs:space_deriv1h{ins=\"$ins\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:fs:space_usage{ins=\"$ins\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Space Exhaust Estimate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node:fs:space_exhaust{ins=\"$ins\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "FD Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filefd_allocated{ins=\"$ins\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node:ins:fd_usage{ins=\"$ins\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_network_info{ins=\"$ins\"}",
     "legendFormat": "INFO"
    },
    {
     "expr": "max by (device) (node_network_mtu_bytes{ins=\"$ins\"})",
     "legendFormat": "MTU"
    },
    {
     "expr": "max by (device) (node_network_speed_bytes{ins=\"$ins\"}) * 8",
     "legendFormat": "Link Speed"
    },
    {
     "expr": "min by (device) (node:dev:network_tx_bytes_rate1m{ins=\"$ins\"})",
     "legendFormat": "Transmit"
    },
    {
     "expr": "min by (device) (node:dev:network_rx_bytes_rate1m{ins=\"$ins\"})",
     "legendFormat": "Receive"
    },
    {
     "expr": "min by (device) (node:dev:network_tx_pps1m{ins=\"$ins\"})",
     "legendFormat": "TX PPS"
    },
    {
     "expr": "min by (device) (node:dev:network_rx_bytes_rate1m{ins=\"$ins\"})",
     "legendFormat": "RX PPS"
    }
   ]
  },
  {
   "title": "Transmit/Receive Packets (Node)",
   "type": "timeseries",
   "description": "▲ for transmit (out) and ▼ for receive (in)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "node:ins:network_tx_pps1m{ins=\"$ins\"}",
     "legendFormat": "▲TX"
    },
    {
     "expr": "- node:ins:network_rx_pps1m{ins=\"$ins\"}",
     "legendFormat": "▼RX"
    }
   ]
  },
  {
   "title": "Transmit/Receive Bandwidth (Node)",
   "type": "timeseries",
   "description": "▲ for transmit (out) and ▼ for receive (in)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:ins:network_tx_bytes_rate1m{ins=\"$ins\"}",
     "legendFormat": "▲{{ device }}"
    },
    {
     "expr": "- node:ins:network_rx_bytes_rate1m{ins=\"$ins\"}",
     "legendFormat": "▼{{ device }}"
    }
   ]
  },
  {
   "title": "Transmit/Receive Packets (Interface)",
   "type": "timeseries",
   "description": "▲ for transmit (out) and ▼ for receive (in)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "node:dev:network_tx_pps1m{ins=\"$ins\", device!=\"lo\"}",
     "legendFormat": "▲{{ device }}"
    },
    {
     "expr": "- node:dev:network_rx_pps1m{ins=\"$ins\", device!=\"lo\"}",
     "legendFormat": "▼{{ device }}"
    }
   ]
  },
  {
   "title": "Transmit/Receive Bandwidth (Interface)",
   "type": "timeseries",
   "description": "▲ for transmit (out) and ▼ for receive (in)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:dev:network_tx_bytes_rate1m{ins=\"$ins\"}",
     "legendFormat": "▲{{ device }}"
    },
    {
     "expr": "- node:dev:network_rx_bytes_rate1m{ins=\"$ins\"}",
     "legendFormat": "▼{{ device }}"
    }
   ]
  },
  { "title": "Protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 } },
  {
   "title": "TCP Segments",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "node:ins:tcp_insegs_rate1m{ins=\"$ins\"}",
     "legendFormat": "▼in"
    },
    {
     "expr": "- node:ins:tcp_outsegs_rate1m{ins=\"$ins\"}",
     "legendFormat": "▲out"
    }
   ]
  },
  {
   "title": "UDP Datagrams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Udp_InDatagrams{ins=\"$ins\"}[5m])",
     "legendFormat": "▼in"
    },
    {
     "expr": "- rate(node_netstat_Udp_OutDatagrams{ins=\"$ins\"}[5m])",
     "legendFormat": "▲out"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{ins=\"$ins\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "TCP Socket Stat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_sockstat_TCP_inuse{ins=\"$ins\"}",
     "legendFormat": "Using"
    },
    {
     "expr": "- node_sockstat_TCP_tw{ins=\"$ins\"}",
     "legendFormat": "Time Wait"
    }
   ]
  },
  {
   "title": "TCP Open",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_netstat_Tcp_ActiveOpens{ins=\"$ins\"}[5m])",
     "legendFormat": "active"
    },
    {
     "expr": "- rate(node_netstat_Tcp_PassiveOpens{ins=\"$ins\"}[5m])",
     "legendFormat": "passive"
    }
   ]
  },
  {
   "title": "TCP Retransmit",
   "type": "timeseries",
   "description": "TCP retransmission segments and rate",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "node:ins:tcp_retranssegs_rate1m{ins=\"$ins\"}",
     "legendFormat": "Retrans Segs"
    },
    {
     "expr": "node:ins:tcp_retrans_ratio1m{ins=\"$ins\"}",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "TCP Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_netstat_TcpExt_ListenDrops{ins=\"$ins\"}[5m])",
     "legendFormat": "Listen Drop"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{ins=\"$ins\"}[5m])",
     "legendFormat": "Retrans"
    },
    {
     "expr": "irate(node_netstat_Tcp_InErrs{ins=\"$ins\"}[5m])",
     "legendFormat": "In Error"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 199 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(node_ntp_offset_seconds{ins=\"$ins\"}))",
     "legendFormat": "NTP Offset"
    },
    {
     "expr": "node_ntp_sanity{ins=\"$ins\"}",
     "legendFormat": "NTP Sanity"
    }
   ]
  },
  {
   "title": "Time Sync",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_sync_status{ins=\"$ins\"}",
     "legendFormat": "Synced"
    },
    {
     "expr": "node_timex_frequency_adjustment_ratio{ins=\"$ins\"}",
     "legendFormat": "Adjust"
    }
   ]
  },
  {
   "title": "NTP Offset",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_ntp_offset_seconds{ins=\"$ins\"}",
     "legendFormat": "Offset"
    },
    {
     "expr": "node_timex_offset_seconds{ins=\"$ins\"}",
     "legendFormat": "Drift"
    }
   ]
  },
  {
   "title": "Node Exporter Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_scrape_collector_duration_seconds{ins=\"$ins\"}",
     "legendFormat": "{{ collector }}"
    }
   ]
  },
  {
   "title": "Hardware Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{ins=\"$ins\"}",
     "legendFormat": "{{ chip }}"
    }
   ]
  }
 ]
}