{
 "title": "PGSQL Instance",
 "description": "PostgreSQL Instance Dashboard",
 "tags": [
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "stat",
   "description": "cls = ${cls}. Used as an unique cluster identifier and resource namespace.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "ins = ${ins}, used as unique instance identifier. Formed as {{ cls }}-{{ seq }}. ",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "table",
   "description": "All instances in pgsql cluster ${cls}",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "pg:ins:status{cls=\"$cls\"}"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\"}"
    }
   ]
  },
  {
   "type": "table",
   "description": "Services in cluster ${cls}. On(green) means current instance are member of that service. Off(orange) means the opposite.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by (proxy) (haproxy_server_status{cls=\"$cls\", server=\"$ins\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "node = ${node}. Node hostname",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:status{ins=\"$ins\"}"
    }
   ]
  },
  {
   "title": "Node IP",
   "type": "stat",
   "description": "ip = ${ip}. Unique identifier for corresponding node",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Node Name",
   "type": "stat",
   "description": "Hostname = ${node}",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Configuration",
   "type": "table",
   "description": "Important configuration entries of this instance",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "pg_meta_info{ins=\"$ins\"}"
    }
   ]
  },
  {
   "type": "table",
   "description": "Database of this Instance ${ins}",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{ins=\"$ins\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg:db:age{ins=\"$ins\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (1 - pg_db_is_template{ins=\"$ins\"} + pg_db_allow_conn{ins=\"$primary\"} * 2)",
     "legendFormat": "Status"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{ins=\"$ins\"})",
     "legendFormat": "Session"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{ins=\"$ins\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{ins=\"$ins\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:conn_usage{ins=\"$ins\"})",
     "legendFormat": "Pool Usage"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{ins=\"$ins\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_disabled{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_paused{ins=\"$ins\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "title": "Aliveness",
   "type": "stat",
   "description": "Aliveness of major components on instance ${ins}\nuptime of node and database. aliveness of postgres, pgbouncer, node and haproxy",
   "gridPos": { "h": 3, "w": 9, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{ins=\"$ins\"}",
     "legendFormat": "Node UP"
    },
    {
     "expr": "pg_uptime{ins=\"$ins\"}",
     "legendFormat": "PG UP"
    },
    {
     "expr": "pg_up{ins=\"$ins\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_up{ins=\"$ins\"}",
     "legendFormat": "pgbouncer"
    },
    {
     "expr": "min(up{ins=\"$ins\", instance=~\".*:(9099|9100)\"})",
     "legendFormat": "node"
    },
    {
     "expr": "time() - haproxy_process_start_time_seconds{ins=\"$ins\"} > bool 0",
     "legendFormat": "haproxy"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "stat",
   "description": "Replication Facts about this instance: In recovery, In sync commit mode, has replication descendant. has publication, has subscription",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_in_recovery{ins=\"$ins\"}",
     "legendFormat": "recovery"
    },
    {
     "expr": "pg_sync_standby_enabled{ins=\"$ins\"}",
     "legendFormat": "sync"
    },
    {
     "expr": "count(pg_repl_lsn{ins=\"$ins\"}) or on() vector(0)",
     "legendFormat": "children"
    },
    {
     "expr": "count by (ins)(pg_pubrel_count{ins=\"$ins\"}) > bool 0 or on() vector(0)",
     "legendFormat": "pub"
    },
    {
     "expr": "count by (ins)(pg_sub_id{ins=\"$ins\"}) or on() vector(0)",
     "legendFormat": "sub"
    },
    {
     "expr": "pg_recv_init_lsn{ins=\"$ins\"} > bool 0",
     "legendFormat": "{{ sender_host }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:ins:cpu_usage{ins=\"$ins\"}",
     "legendFormat": "Node"
    },
    {
     "expr": "pg:ins:load1{ins=\"$ins\"} != -1",
     "legendFormat": "Postgres"
    },
    {
     "expr": "pgbouncer:ins:load1{ins=\"$ins\"} != -1",
     "legendFormat": "Pgbouncer"
    },
    {
     "expr": "haproxy:ins:usage{ins=\"$ins\"}",
     "legendFormat": "Haproxy"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:ins:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}",
     "legendFormat": "RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rate1m{ins=\"$ins\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:ins:waiting_clients{ins=\"$ins\"}",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cls,ins)(pg_repl_replay_lag{ins=\"$ins\"} or pg:ins:lag_seconds{ins=\"$ins\"} or pg_lag{ins=\"$ins\"})",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{ins=\"$ins\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ins:pressure1{ins=\"$ins\"}",
     "legendFormat": "Pressure"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:ins:cpu_usage, pg:ins:load, pgbouncer:ins:load)",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ins:pressure1{ins=\"$ins\"}",
     "legendFormat": "p1"
    },
    {
     "expr": "ins:pressure5{ins=\"$ins\"}",
     "legendFormat": "p5"
    },
    {
     "expr": "ins:pressure15{ins=\"$ins\"}",
     "legendFormat": "p15"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{ins=\"$ins\", alertstate=\"firing\"}) or on() vector(0)",
     "legendFormat": "Alert"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represent an alerting Event. Gray transparent stipe are pending alerts.",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}}"
    },
    {
     "expr": "ALERTS{ins=\"$ins\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}}"
    }
   ]
  }
 ]
}