{
 "title": "PGSQL Queries",
 "description": "PostgreSQL Queries for single Instance",
 "tags": [
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS Seasonality",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(query) (rate(pg_query_calls[5m]))",
     "legendFormat": "QPS"
    },
    {
     "expr": "sum without(query) (rate(pg_query_calls[5m] OFFSET 1d))",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "sum without(query) (rate(pg_query_calls[5m] OFFSET 2d))",
     "legendFormat": "2 Day Ago"
    }
   ]
  },
  {
   "title": "Average Queries per Xact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum without(query) (rate(pg_query_calls[1m]))) / on(ins) group_left() pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "Q"
    }
   ]
  },
  {
   "title": "Long Run Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_duration{ins=\"$ins\", state!~\"(idle.*|disabled)\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Average Queries per Commit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum without(query) (rate(pg_query_calls[1m]))) / on(ins) group_left() pg:ins:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "Q"
    }
   ]
  },
  {
   "title": "Query QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Table Scan 'QPS'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "pg:table:scan_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "Pgbouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum without(query) (rate(pg_query_calls[1m])))",
     "legendFormat": "1m"
    },
    {
     "expr": "(sum without(query) (rate(pg_query_calls[5m])))",
     "legendFormat": "5m"
    },
    {
     "expr": "(sum without(query) (rate(pg_query_calls[15m])))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "Pgbouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum without(query) (rate(pg_query_exec_time[1m]))) / (sum without(query) (rate(pg_query_calls[1m]))) / 1000",
     "legendFormat": "1m"
    },
    {
     "expr": "(sum without(query) (rate(pg_query_exec_time[5m]))) / (sum without(query) (rate(pg_query_calls[5m]))) / 1000",
     "legendFormat": "5m"
    },
    {
     "expr": "(sum without(query) (rate(pg_query_exec_time[15m]))) / (sum without(query) (rate(pg_query_calls[15m]))) / 1000",
     "legendFormat": "15m"
    }
   ]
  },
  { "title": "Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Statements",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (datname, query) (pg_query_calls{ins=\"$ins\"}) > 0",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg_query_exec_time{ins=\"$ins\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:rt_1m{ins=\"$ins\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:call_rate1m{ins=\"$ins\"})",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement Time Spent 1h",
   "type": "piechart",
   "description": "Time spent on executing statements  during last 1 hour",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\"}[1h])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement Call 1h",
   "type": "piechart",
   "description": "number of statement call in last 1 hour",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pg_query_calls{ins=\"$ins\"}[1h])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query Call",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement RT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:query:rt_1m{ins=\"$ins\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement RT Ranking",
   "type": "graph",
   "description": "Rank of last 1m RT",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(32, increase(pg_query_exec_time{ins=\"$ins\"}[1h]) / increase(pg_query_calls{ins=\"$ins\"}[1h]))",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Statement Time Spent rate1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\"}[5m])",
     "legendFormat": "{{ query }}"
    }
   ]
  }
 ]
}