{
 "title": "PGSQL Activity",
 "description": "PostgreSQL Queries for single Instance",
 "tags": [
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Pressure 1m",
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:ins:cpu_usage, pg:ins:load, pgbouncer:ins:load)",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cls:pressure1{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "CPU Usage 1m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:cls:cpu_usage_1m{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "node:ins:cpu_usage_1m{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "node:ins:cpu_usage_1m{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Read/Write Bandwidth",
   "type": "timeseries",
   "description": "▲ for read bandwidth, ▼ for write bandwidth",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:ins:disk_read_bytes_rate1m{cls=\"$cls\"}",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- node:ins:disk_write_bytes_rate1m{cls=\"$cls\"}",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Transmit/Receive Bandwidth (Interface)",
   "type": "timeseries",
   "description": "▲ for transmit (out) and ▼ for receive (in)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:ins:network_tx_bytes_rate1m{cls=\"$cls\"}",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- node:ins:network_rx_bytes_rate1m{cls=\"$cls\"}",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Postgres Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "Postgres Backends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Postgres Backends (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Xacts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Cluster Xact Commit Rate",
   "type": "timeseries",
   "description": "Postgres transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:cls:xact_commit_rate1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:cls:xact_commit_rate5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:cls:xact_commit_rate15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Cluster Xact Rollback",
   "type": "timeseries",
   "description": "Postgres rollbacked transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:cls:xact_rollback_rate1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:cls:xact_rollback_rate5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:cls:xact_rollback_rate15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Transaction Commit by Instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:ins:xact_commit_rate1m{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_commit_rate1m{cls=\"$cls\", ins!=\"$primary\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Instances (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  }
 ]
}