version: "2.1"
services:
  flink:
    container_name: flink
    build:
      context: flink
    expose:
      - "6123"
    ports:
      - "8081:8081"
      - "8089:8089"
    command: jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink

  taskmanager:
    build:
      context: flink
    expose:
      - "6121"
      - "6122"
    depends_on:
      - flink
    command: taskmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink
    links:
      - "flink:flink"
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zeppelin:
    container_name: zeppelin
    build:
      context: zeppelin
    environment:
      ZEPPELIN_NOTEBOOK_DIR: /notebook
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/notebooks:/notebook"

