# config file version
apiVersion: 1

deleteDatasources:
  - name: loki
  - name: jaeger

datasources:
- name: loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  jsonData:
    derivedFields:
    - datasourceUid: jaeger
      matcherRegex: traceID=(\w+)
      url: '$${__value.raw}'
      name: TraceID
- name: tempo
  type: tempo
  uid: tempo
  access: proxy
  url: http://tempo-query:16686
  isDefault: false
  version: 1
  editable: false
  basicAuth: false
- name: jaeger
  type: jaeger
  uid: jaeger
  access: proxy
  url: http://jaeger:16686
  isDefault: false
  version: 1
  editable: false
  basicAuth: false
- name: prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: false
  version: 1
  editable: false
  basicAuth: false
  jsonData:
    httpMethod: 'GET'
    exemplarTraceIDDestination:
      name: 'traceID'
      url: 'http://localhost:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22tempo%22,%7B%22query%22:%22$${value}%22%7D%5D'