version: '2.3'
services:
  flask-mongodb:
    build:
      context: ..
      target: base
    command: compose/develop
    environment:
      PYTHONPATH: .
    ports:
      - '27017:27017' # mongodb
      - '5000:5000' # flask
    volumes:
      - ..:/app
      - ..:/data/db
