version: '3'

services:
  sentiment:
    restart: always
    build:
      context: .
    environment:
      SERVICE_PORTS: 5000
    command: bash start.sh 2
  lstm-haproxy:
    image: dockercloud/haproxy
    depends_on:
      - sentiment
    links:
      - sentiment
    ports:
      - '5000:80'
    container_name: sentiment-haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
