version: '2.3'
services:
  hive:
    build:
      context: hive
      target: base
    container_name: hive
    command: bash start.sh
    ports:
      - '8088:8088'
      - '9000:9000'
      - '9870:9870'
      - '9864:9864'
      - '19888:19888'
      - '10000:10000'
      - '8042:8042'
  
  nifi:
    build:
      context: nifi
      target: base
    container_name: nifi
    ports:
      - '8080:8080'
  
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: mysql