# https://github.com/bitnami/bitnami-docker-postgresql/blob/master/docker-compose-replication.yml

version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    container_name: postgresql
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
      - './postgres:/bitnami/postgresql/conf/'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgresql_master_data:
    driver: local
  
