version: '2.3'
services:
  pyspark:
    build:
      context: ..
      target: base
    command: compose/develop
    ports:
      - '8080:8080'
      - '8088:8088'
      - '9000:9000'
      - '9870:9870'
      - '9864:9864'
      - '19888:19888'
      - '8042:8042'
