version: '2.3'
services:
  hive:
    build:
      context: .
      target: base
    container_name: hive
    command: bash start.sh
    ports:
      - '8088:8088'
      - '9000:9000'
      - '9870:9870'
      - '9864:9864'
      - '19888:19888'
      - '10000:10000'
      - '8042:8042'
