version: '2.3'
services:
  flask-rest:
    build:
      context: ..
      target: base
    command: bash eventlet.sh
    environment:
      PYTHONPATH: .
    ports:
      - '5000:5000' # flask
    volumes:
      - ..:/app
