version: '2.3'
services:
  kafka-flask:
    build:
      context: ..
      target: base
    command: compose/develop
    environment:
      PYTHONPATH: .
    ports:
      - '5000:5000'
      - '2181:2181'
      - '9092:9092'
      - '9000:9000'
